apiVersion: v1
kind: Service
metadata:
  name: member-management-context
  labels:
    app: member-management-context
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: member-management-context